version: '3'
services:
  web:
    restart: 'always'
    build: ./
    command: php -S 0.0.0.0:8001 /app/src/Web/index.php
    ports:
      - "8001:8001"
    volumes:
     - .:/app

  worker:
    restart: 'always'
    build: ./
    command: php /app/src/start.php
    volumes:
      - .:/app

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app